// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: VNC_CONNECT

#ifndef _VNC_CONNECT_UI_H
#define _VNC_CONNECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Index
void ui_Index_screen_init(void);
extern lv_obj_t *ui_Index;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label1;
void ui_event_host( lv_event_t * e);
extern lv_obj_t *ui_host;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Label3;
void ui_event_port( lv_event_t * e);
extern lv_obj_t *ui_port;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Label2;
void ui_event_password( lv_event_t * e);
extern lv_obj_t *ui_password;
void ui_event_connect_btn( lv_event_t * e);
extern lv_obj_t *ui_connect_btn;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_loading;
void ui_event_keyboard( lv_event_t * e);
extern lv_obj_t *ui_keyboard;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
